apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "tasks", "namespace": "", "kind": "DeploymentConfig"}]'
  labels:
    name: tasks-pipeline
  name: tasks-pipeline
spec:
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
          node('maven') {
             stage ('Compile') {
               git 'http://<YOUR USER>-gogs.apps.bogota-e028.openshiftworkshop.com/testdrive/openshift-tasks-testdrive.git'
               sh "mvn clean install -DskipTests=true"
             }

             stage('Deploy') {
               sh "oc start-build tasks-app --from-file target/openshift-tasks.war --follow --wait=true  --namespace <YOUR USER>" 
             }
          }
    type: JenkinsPipeline
  triggers:
  - github:
      secret: CzgPZAZ5m2
    type: GitHub
  - generic:
      secret: CzgPZAZ5m2
    type: Generic
